"""user_permissions

Revision ID: 2461f952766e
Revises: 75bc2b2cf80d
Create Date: 2023-10-16 19:06:37.211782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from main import PermissionEnum

# revision identifiers, used by Alembic.
revision: str = '2461f952766e'
down_revision: Union[str, None] = '75bc2b2cf80d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # PermissionEnum.create(op.get_bind(), checkfirst=True)
    permission_enum = postgresql.ENUM('super_admin', 'admin', 'basic', name='permission', create_type=False)
    permission_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('permission', permission_enum, nullable=False, server_default="basic"))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'permission')
    # ### end Alembic commands ###
