"""books_table

Revision ID: 5433e2cfbcc0
Revises: 7853ad5b7c89
Create Date: 2023-10-17 18:58:59.847046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5433e2cfbcc0'
down_revision: Union[str, None] = '7853ad5b7c89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('title', sa.VARCHAR(length=250), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('author', sa.VARCHAR(length=100), nullable=True),
    sa.Column('isbn10', sa.VARCHAR(length=10), nullable=True),
    sa.Column('isbn13', sa.VARCHAR(length=15), nullable=True),
    sa.Column('publish_date', sa.DATE(), nullable=True),
    sa.Column('best_seller', sa.BOOLEAN(), server_default='no', nullable=True),
    sa.Column('top_rated', sa.BOOLEAN(), server_default='no', nullable=True),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), server_default='0', nullable=True),
    sa.Column('review_count', sa.INTEGER(), server_default='0', nullable=True),
    sa.Column('price', sa.Numeric(precision=5, scale=2), server_default='99', nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
