"""isbn_varchar_16_fix

Revision ID: 5a06fdd6edd4
Revises: 559f6355f147
Create Date: 2023-10-17 19:06:01.925283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a06fdd6edd4'
down_revision: Union[str, None] = '559f6355f147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'isbn13',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'isbn13',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    # ### end Alembic commands ###
