"""user_created_at_optional_2

Revision ID: 75bc2b2cf80d
Revises: 670b148f886d
Create Date: 2023-10-16 15:08:25.987959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75bc2b2cf80d'
down_revision: Union[str, None] = '670b148f886d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
