"""table_cleanup

Revision ID: 7853ad5b7c89
Revises: 
Create Date: 2023-10-17 18:29:21.351034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7853ad5b7c89'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'permission')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('permission', postgresql.ENUM('super_user', 'user', 'basic', name='permission'), server_default=sa.text("'basic'::permission"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
