"""Initial

Revision ID: e1d30c131892
Revises: 
Create Date: 2023-10-15 16:46:00.208000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1d30c131892'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('books')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('isbn10', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('isbn13', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('publish_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('best_seller', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('top_rated', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.NUMERIC(precision=2, scale=1), autoincrement=False, nullable=True),
    sa.Column('review_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('edition', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='books_pkey')
    )
    op.drop_table('users')
    # ### end Alembic commands ###
