"""add_edition

Revision ID: fcd82212a33e
Revises: 5433e2cfbcc0
Create Date: 2023-10-17 19:01:38.317847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcd82212a33e'
down_revision: Union[str, None] = '5433e2cfbcc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('edition', sa.INTEGER(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'edition')
    # ### end Alembic commands ###
